name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.3

      - name: Install dependencies
        run: |
          go mod download

      - name: Build and test coverage
        run: |
          go build -v ./...
          go test ./middleware ./routes ./database -coverprofile=cover.txt
